apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ include "application.name" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPorts.http }}
  selector:
    app: {{ include "application.name" . }}
